---
title: "README"
output: github_document
date: "2023-05-09"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### The final project PDF can be viewed [HERE](https://github.com/TianCater/DSGE_BVAR_Estimation/blob/main/R_markdown_ts_dsge_bvar/R_project.pdf) in the repo above.

## Purpose

This project replicates the New Keynesian model composed by Belongia & Ireland (2020), estimated using
Bayesian techniques, to reflect the recent post-financial-crisis episode of zero nominal interest rates in the US,
and demonstrates the effects of substituting the Federal Reserve’s traditional policy of managing interest rates
with the alternative of money growth targeting. In addition, the sample is extended to the most recent data available to test the robustness of the findings. 

For both the benchmark and extended sample, counterfactual simulations illustrate similar findings to Belongia & Ireland (2020); a rule for modifying the money growth ratemodestly and gradually in response to deviations in the output gap has performance levels comparable to the
calibrated interest rate rule in stabilising inflation and output. Additionally, the impulse responses disclose that,
under the same money growth rule, the US’s post-2008 crisis economic recovery would have been accelerated
due to a significantly shorter period of near-zero nominal interest rates. 

These findings insinuate that, with a binding zero lower bound constraint, policy rules for money growth can provide a simplistic method for
monetary policy to reduce the uneasiness of monetary policy efficacy.


## Code

The Bayesian estimmation code was conducted using Dynare. The code can be provided upon an emailed request.

